# Generated by Django 5.1.5 on 2025-01-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
