# Generated by Django 5.1.5 on 2025-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ui', '0002_uploadedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
