# Generated by Django 5.1.5 on 2025-04-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ui', '0003_queryhistory_image_alter_queryhistory_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='queryhistory',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
