# Generated by Django 5.1.5 on 2025-04-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ui', '0004_queryhistory_file_name_queryhistory_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryhistory',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='queryhistory',
            name='file_type',
        ),
    ]
