# Generated by Django 5.1.5 on 2025-04-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ui', '0005_remove_queryhistory_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='pdf_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
